[project]
name = "micropython-getting-started"
version = "0.1.0"
description = "A getting started guide for MicroPython"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.6.12",
]
